"""added start time to shows

Revision ID: 142cd842d67a
Revises: 3ceaa449c7d0
Create Date: 2023-03-05 14:21:33.236150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142cd842d67a'
down_revision = '3ceaa449c7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
