"""added seeking description to Artists

Revision ID: 97800e8d0ce9
Revises: f84198e554df
Create Date: 2023-03-03 12:17:21.998554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97800e8d0ce9'
down_revision = 'f84198e554df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
